export const TasksData = [
  {
    id: 1,
    title: "Buy groceries",
    description: "Milk, eggs, bread, and fruits",
    group: "personal",
    priority: "medium",
    done: false,
  },
  {
    id: 2,
    title: "Prepare presentation",
    description: "Finalize slides for Monday’s meeting",
    group: "work",
    priority: "high",
    done: false,
  },
  {
    id: 3,
    title: "Book dentist appointment",
    description: "Call Dr. Smith’s office to schedule cleaning",
    group: "personal",
    priority: "low",
    done: true,
  },
  {
    id: 4,
    title: "Fix styling bug",
    description: "Resolve overlapping button on mobile view",
    group: "work",
    priority: "high",
    done: false,
  },
  {
    id: 5,
    title: "Plan weekend hike",
    description: "Research trails and pack essentials",
    group: "other",
    priority: "low",
    done: false,
  },
  {
    id: 6,
    title: "Write blog post",
    description: "Draft article about CSS variables",
    group: "personal",
    priority: "medium",
    done: false,
  },
  {
    id: 7,
    title: "Pay utility bills",
    description: "Electricity and water due by the end of week",
    group: "other",
    priority: "high",
    done: true,
  },
  {
    id: 8,
    title: "Team code review",
    description: "Review PRs on GitHub and leave comments",
    group: "work",
    priority: "medium",
    done: false,
  },
];
